console.log("==================STRING 1===========================")
let str='Hello world';
console.log(str.toUpperCase())
console.log(str.toLowerCase())
console.log(str.charAt())
console.log(str.indexOf('lo',4))
console.log(str.includes('l',3))
console.log(str.replace('llo','lllppp'))
console.log(str.search('lo'))
console.log(str.trim())
console.log(str.substr(1,5))
console.log(str.concat('rahul'))
console.log(str.split(4,7))

console.log("==================STRING 2===========================")
let aa='Hello world';
console.log(aa.toUpperCase())
console.log(aa.toLowerCase())
console.log(aa.charAt())
console.log(aa.indexOf('lo',4))
console.log(aa.includes('l',3))
console.log(aa.replace('llo','lllppp'))
console.log(aa.search('lo'))
console.log(aa.trim())
console.log(aa.substr(1,5))
console.log(aa.concat('rahul'))
console.log(aa.split(4,7))
console.log("==================STRING 3===========================")
let str1='Hello world';
console.log(str1.toUpperCase())
console.log(str1.toLowerCase())
console.log(str1.charAt())
console.log(str1.indexOf('lo',4))
console.log(str1.includes('l',3))
console.log(str1.replace('llo','lllppp'))
console.log(str1.search('lo'))
console.log(str1.trim())
console.log(str1.substr(1,5))
console.log(str1.concat('rahul'))
console.log(str1.split(4,7))
console.log("==================STRING 4===========================")
let str2='Hello world';
console.log(str2.toUpperCase())
console.log(str2.toLowerCase())
console.log(str2.charAt())
console.log(str2.indexOf('lo',4))
console.log(str2.includes('l',3))
console.log(str2.replace('llo','lllppp'))
console.log(str2.search('lo'))
console.log(str2.trim())
console.log(str2.substr(1,5))
console.log(str2.concat('rahul'))
console.log(str2.split(4,7))
console.log("==================STRING 5===========================")
let str3='Hello world';
console.log(str3.toUpperCase())
console.log(str3.toLowerCase())
console.log(str3.charAt())
console.log(str3.indexOf('lo',4))
console.log(str3.includes('l',3))
console.log(str3.replace('llo','lllppp'))
console.log(str3.search('lo'))
console.log(str3.trim())
console.log(str3.substr(1,5))
console.log(str3.concat('rahul'))
console.log(str3.split(4,7))
console.log("==================STRING 6===========================")
let str4='Hello world';
console.log(str4.toUpperCase())
console.log(str4.toLowerCase())
console.log(str4.charAt())
console.log(str4.indexOf('lo',4))
console.log(str4.includes('l',3))
console.log(str4.replace('llo','lllppp'))
console.log(str4.search('lo'))
console.log(str4.trim())
console.log(str4.substr(1,5))
console.log(str4.concat('rahul'))
console.log(str4.split(4,7))
console.log("==================STRING 7===========================")
let str5='Hello world';
console.log(str5.toUpperCase())
console.log(str5.toLowerCase())
console.log(str5.charAt())
console.log(str5.indexOf('lo',4))
console.log(str5.includes('l',3))
console.log(str5.replace('llo','lllppp'))
console.log(str5.search('lo'))
console.log(str5.trim())
console.log(str5.substr(1,5))
console.log(str5.concat('rahul'))
console.log(str5.split(4,7))
console.log("==================STRING 8===========================")
let str6='Hello world';
console.log(str6.toUpperCase())
console.log(str6.toLowerCase())
console.log(str6.charAt())
console.log(str6.indexOf('lo',4))
console.log(str6.includes('l',3))
console.log(str6.replace('llo','lllppp'))
console.log(str6.search('lo'))
console.log(str6.trim())
console.log(str6.substr(1,5))
console.log(str6.concat('rahul'))
console.log(str6.split(4,7))
console.log("==================STRING 9===========================")
let str7='Hello world';
console.log(str7.toUpperCase())
console.log(str7.toLowerCase())
console.log(str7.charAt())
console.log(str7.indexOf('lo',4))
console.log(str7.includes('l',3))
console.log(str7.replace('llo','lllppp'))
console.log(str7.search('lo'))
console.log(str7.trim())
console.log(str7.substr(1,5))
console.log(str7.concat('rahul'))
console.log(str7.split(4,7))
console.log("==================STRING 10===========================")
let str8='Hello world';
console.log(str8.toUpperCase())
console.log(str8.toLowerCase())
console.log(str8.charAt())
console.log(str8.indexOf('lo',4))
console.log(str8.includes('l',3))
console.log(str8.replace('llo','lllppp'))
console.log(str8.search('lo'))
console.log(str8.trim())
console.log(str8.substr(1,5))
console.log(str8.concat('rahul'))
console.log(str8.split(4,7))